language: node_js

cache:
  directories:
    - /home/travis/.elm/0.19.0/package

os:
  - linux

env:
  matrix:
    - ELM_VERSION=0.18.0 TARGET_NODE_VERSION=node

before_install:
  - node --version
  - npm --version
  - npm install -g elm@$ELM_VERSION

install:
  - npm install

script:
  - npm run build-ci
