language: node_js

cache:
  directories:
    - /home/travis/.elm/0.19.0/package

os:
  - linux

before_install:
  - node --version
  - npm --version
  - npm install -g elm

install:
  - npm install

script:
  - npm run build-ci
