environment:
  matrix:
  - nodejs_version: "4.6"

platform:
  - x64

matrix:
  fast_finish: true

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
  - node --version
  - npm --version
  - npm install -g elm
  - npm install

build_script:
  - npm run build-ci

build: off
